/**
 * notes.ts - TanStack Query 5.x mutation hook for F-002 AI Note Generation.
 *
 * The endpoint POST /api/notes/generate accepts a relationship-context
 * string and returns AI-generated outreach talking points produced by
 * Anthropic Claude (via Langchain on the backend per AAP Sec 0.4.4).
 *
 * Hook exposed:
 *   - useGenerateNotesMutation()  POST /api/notes/generate
 *
 * Type-level helpers also exposed (consumed by AddEditConnectionForm.tsx):
 *   - GenerateNotesRequest   request payload shape
 *   - GenerateNotesResponse  response payload shape
 *   - AiNoteErrorCode        union of known backend error codes
 *   - isSoftAiFailure        type guard distinguishing soft from hard failures
 *
 * Configuration (per AAP Sec 0.7.3 and assigned-folder requirements):
 *   - retry: 0
 *       Mutations never retry by default in this project (the QueryClient
 *       global default is also 0). We set it explicitly here as
 *       documentation: a 5-second timeout has already exhausted the
 *       budget; retrying would compound the user's wait time without
 *       meaningfully increasing success probability.
 *   - throwOnError: false (inherited from the QueryClient default)
 *       Errors flow through onError so the AddEditConnectionForm can
 *       distinguish soft failures (504 ai_timeout, 502 ai_unavailable)
 *       from hard failures (422, 401, 403, 500). Soft failures render
 *       an inline non-blocking banner; hard failures show a toast.
 *
 * Per AAP Sec 0.4.4, this hook does NOT couple to POST /api/connections.
 * The form's two-call flow is:
 *   1. (optional) useGenerateNotesMutation -> server returns ai_notes
 *   2. user reviews/edits the ai_notes textarea
 *   3. useCreateConnectionMutation -> server persists the record
 *
 * AI failure NEVER blocks form submission; the contributor may type
 * their own notes or leave ai_notes blank.
 *
 * Coordination touchpoints:
 *   - @/api/client            apiPost<TResp, TReq>(path, body), ApiError
 *   - @/components/ui/Toast   useToast() returns the toast.{success,error,...} facade.
 *                              Note: Toast.tsx exposes the toast object via the
 *                              useToast() hook rather than as a module-level
 *                              singleton. We invoke useToast() inside
 *                              useGenerateNotesMutation so that the onError
 *                              closure can call toast.error(...) for HARD
 *                              failures only. This is allowed because
 *                              useGenerateNotesMutation is itself a hook.
 *   - @tanstack/react-query   useMutation, UseMutationResult (type-only).
 */

import { useMutation, type UseMutationResult } from "@tanstack/react-query";

import { apiPost, type ApiError } from "@/api/client";
import { useToast } from "@/components/ui/Toast";

// ---------------------------------------------------------------------------
// Request and response shapes
// ---------------------------------------------------------------------------

/**
 * Request payload for `POST /api/notes/generate`.
 *
 * Mirrors backend `app.schemas.note_generation.NoteGenerationRequest`
 * field-for-field. Constraints (validated server-side):
 *   - relationship_context: 1-4000 characters; whitespace-stripped.
 *   - No additional fields permitted (extra="forbid" on the backend).
 *
 * The form (AddEditConnectionForm) validates these constraints
 * client-side via Zod (the connection schema's relationship_context
 * field) before invoking the mutation. Server-side validation is the
 * authoritative check per AAP Sec 0.7.1.
 */
export interface GenerateNotesRequest {
  relationship_context: string;
}

/**
 * Response payload for `POST /api/notes/generate`.
 *
 * Mirrors backend `app.schemas.note_generation.NoteGenerationResponse`
 * field-for-field.
 *
 * Fields:
 *   ai_notes      The AI-generated text. Server-side sanitized; safe
 *                 to render directly into a textarea element. May be
 *                 empty in edge cases (Claude returned a very short
 *                 output); the form decides whether empty AI notes
 *                 warrant a "no useful suggestion generated" hint.
 *   model         The Claude model identifier (e.g., "claude-sonnet-4-5").
 *                 Informational only; the SPA may render
 *                 "Generated by <model>" but does NOT branch logic on
 *                 this value (provider replaceability per AAP Sec 0.4.4
 *                 means the model name could change without SPA changes).
 *   generated_at  ISO-8601 UTC timestamp with offset (e.g.,
 *                 "2026-04-23T10:30:00+00:00"). Typed as string (not
 *                 Date) because the backend serializes to ISO-8601;
 *                 form components parse via new Date(generated_at) for
 *                 the "Generated N minutes ago" hint.
 */
export interface GenerateNotesResponse {
  ai_notes: string;
  model: string;
  generated_at: string;
}

// ---------------------------------------------------------------------------
// Error code taxonomy
// ---------------------------------------------------------------------------

/**
 * Backend error codes returned by `POST /api/notes/generate`.
 *
 * The SPA's AddEditConnectionForm uses these to distinguish soft
 * failures (where the form should still submit per AAP Sec 0.4.4)
 * from hard failures.
 *
 *   "ai_timeout"        The 5-second watchdog elapsed before Claude
 *                       responded. Soft failure: render inline banner
 *                       "AI unavailable; you can still submit".
 *   "ai_unavailable"    Anthropic provider returned an error (auth
 *                       failure, rate limit, model unavailable, etc.).
 *                       Soft failure (same affordance).
 *   "forbidden"         Viewer (Sales Rep) role attempted to call this
 *                       endpoint. The form button should be hidden
 *                       entirely for Viewers via RoleGate; this code
 *                       surfaces only on RBAC bypass attempts.
 *   "validation_failed" Body-level pydantic validation failure (the
 *                       form's Zod validation should catch most of
 *                       these before they reach the server).
 *   "invalid_json"      The request body was not valid JSON.
 *
 * Other ApiError.code values (auth_required, server_error,
 * network_error, etc.) are treated as hard failures by the form. The
 * union accepts an arbitrary string as the catch-all to keep the type
 * forward-compatible: a future backend release may introduce new error
 * codes (for example, "rate_limited" once per-user throttling is added)
 * without breaking compilation here.
 */
export type AiNoteErrorCode =
  | "ai_timeout"
  | "ai_unavailable"
  | "forbidden"
  | "validation_failed"
  | "invalid_json"
  // Catch-all for forward compatibility (network_error, server_error,
  // auth_required, future codes, etc.). The string broadens the union;
  // call sites that switch on AiNoteErrorCode receive autocomplete for
  // the named codes while still compiling against unknown ones.
  | (string & {});

// ---------------------------------------------------------------------------
// Soft-vs-hard failure classifier
// ---------------------------------------------------------------------------

/**
 * Type-guard helper for callers (form components) that need to
 * distinguish soft AI failures from hard errors.
 *
 * Returns true if the error is a soft AI failure (504 ai_timeout or
 * 502 ai_unavailable) per AAP Sec 0.4.4. Callers use this to choose
 * between the inline banner ("AI unavailable; you can still submit")
 * and a hard-error toast.
 *
 * Accepts `null | undefined` as well as ApiError so callers can pass
 * `mutation.error` directly without a guard. TanStack Query types
 * `mutation.error` as `TError | null`, which becomes `ApiError | null`
 * here; the helper short-circuits on missing values.
 *
 * @param error - The mutation error, possibly null/undefined.
 * @returns       True iff the error code is "ai_timeout" or
 *                "ai_unavailable".
 *
 * @example
 *   const mutation = useGenerateNotesMutation();
 *   // ...later in render:
 *   if (mutation.isError && isSoftAiFailure(mutation.error)) {
 *     return <InlineSoftFailureBanner />;
 *   }
 */
export function isSoftAiFailure(error: ApiError | null | undefined): boolean {
  if (!error) {
    return false;
  }
  return error.code === "ai_timeout" || error.code === "ai_unavailable";
}

// ---------------------------------------------------------------------------
// Mutation hook
// ---------------------------------------------------------------------------

/**
 * `useMutation` hook for AI note generation (F-002).
 *
 * Variables type:   GenerateNotesRequest
 * Result data type: GenerateNotesResponse
 * Error type:       ApiError
 *
 * Behavior:
 *   - retry: 0
 *       Explicit override of the QueryClient default (which is also 0
 *       for mutations) to make the no-retry behavior visible at the
 *       hook definition. AI generation already has a 5-second timeout
 *       budget; retrying would compound the wait time.
 *
 *   - onSuccess
 *       NO toast.success here. The form renders the returned ai_notes
 *       directly into an editable textarea; firing a separate "AI
 *       notes generated" toast would be redundant and pull focus.
 *
 *   - onError
 *       For SOFT failures (ai_timeout, ai_unavailable per AAP Sec 0.4.4):
 *         do NOT show a toast. The form component reads
 *         mutation.error and renders an inline banner instead. This
 *         lets the user keep working without dismissing a modal/toast.
 *       For HARD failures (validation, auth, RBAC, server):
 *         show a toast.error so the user has clear feedback that the
 *         AI button click failed.
 *
 *   - throwOnError: false (inherited from the QueryClient default)
 *       Errors flow through onError; never thrown into the React error
 *       boundary. The form component handles error state via
 *       mutation.error.
 *
 * The hook calls `useToast()` at its top level (a hook call inside a
 * hook is allowed by the React rules of hooks) so the onError closure
 * can reference the stable toast facade.
 *
 * @returns The TanStack Query mutation result. The form component
 *          accesses `mutation.mutate(payload)`, `mutation.data?.ai_notes`,
 *          `mutation.isPending`, `mutation.isError`, and `mutation.error`.
 */
export function useGenerateNotesMutation(): UseMutationResult<
  GenerateNotesResponse,
  ApiError,
  GenerateNotesRequest
> {
  // useToast() returns a memoized facade; calling it here (inside the
  // hook) lets the onError closure capture toast.error(...). The
  // returned object is referentially stable across renders so the
  // mutation config object's identity does not churn.
  const toast = useToast();

  return useMutation<GenerateNotesResponse, ApiError, GenerateNotesRequest>({
    mutationFn: (payload) =>
      apiPost<GenerateNotesResponse, GenerateNotesRequest>("/api/notes/generate", payload),
    retry: 0,
    onError: (error) => {
      // Soft AI failures (504 timeout / 502 provider error) are surfaced
      // by the form as an inline banner per AAP Sec 0.4.4; do NOT toast.
      if (isSoftAiFailure(error)) {
        return;
      }
      // Hard failures (validation, auth, RBAC, server) get a toast so
      // the user has clear feedback that the AI button click failed.
      // ApiError.message is always populated (the client.ts helper
      // falls back to a default-message-for-status string when the
      // backend envelope is malformed), so the ?? branch is defensive.
      toast.error(error.message || "Failed to generate AI notes.");
    },
  });
}
