"""Flask extension singletons for the Sales-Connections backend.

This module instantiates extension singletons at import time and binds
them to a specific Flask app via ``init_app(app)`` from within the
application factory in :mod:`app.__init__`. The pattern mirrors the
classic Flask-extension idiom (``ext = Extension(); ext.init_app(app)``)
without introducing ``flask-sqlalchemy`` or any other heavyweight Flask
plugin that would coerce the project away from the explicit
transaction-boundary discipline mandated by the AAP.

Singletons exposed by this module:
    * ``db`` - thin SQLAlchemy 2.x wrapper exposing ``engine``,
      ``Session`` (sessionmaker), ``metadata`` (Base.metadata), ``Base``
      (DeclarativeBase subclass), plus ``init_app(app)``, ``session()``,
      and ``dispose()`` lifecycle helpers.
    * ``oauth`` - Authlib ``OAuth`` registration table; per-app provider
      registration is deferred to :func:`init_oauth_clients`.
    * ``logger`` - module-level :class:`structlog.stdlib.BoundLogger`
      bound to the namespace ``"app"``. Picks up the structlog
      configuration applied during :func:`app.create_app` the first
      time it logs.
    * ``metrics_registry`` - dedicated :class:`prometheus_client.CollectorRegistry`
      instance kept separate from the default ``REGISTRY`` so that
      multiple Flask apps (e.g., test fixtures) do not collide on
      duplicate metric registrations.

CRITICAL: The ``db`` singleton is a custom thin wrapper around bare
SQLAlchemy 2.x - NOT ``flask-sqlalchemy``. The wrapper exposes
``init_app(app)`` to consume the Flask config and construct the Engine
plus Session factory at app creation time, but it deliberately omits
flask-sqlalchemy's automatic teardown handler and query-property
abstractions. Service-layer code owns transaction lifecycles
explicitly via ``with db.session() as session: with session.begin():``
blocks (see AAP section 0.5.3 - "Service functions own transactions").

CRITICAL: Importing this module MUST NOT cause network I/O, database
connections, log emission, or any other observable side effect beyond
the construction of the singletons themselves. The module is the
foundation that every other ``app.*`` module depends on; any side
effect here would propagate into every test invocation.
"""

from __future__ import annotations

import contextlib
from typing import TYPE_CHECKING

from authlib.integrations.flask_client import OAuth
from prometheus_client import (
    CollectorRegistry,
    GCCollector,
    PlatformCollector,
    ProcessCollector,
)
from sqlalchemy import MetaData, create_engine
from sqlalchemy.engine.url import make_url
from sqlalchemy.orm import DeclarativeBase, Session as SQLAlchemySession, sessionmaker
import structlog

if TYPE_CHECKING:
    from flask import Flask
    from sqlalchemy import Engine


__all__ = [
    "NAMING_CONVENTION",
    "Base",
    "SQLAlchemy",
    "db",
    "init_oauth_clients",
    "logger",
    "metrics_registry",
    "oauth",
]


# ---------------------------------------------------------------------------
# SQLAlchemy 2.x Naming Convention + Declarative Base
# ---------------------------------------------------------------------------
# Stable constraint naming is essential for clean Alembic migrations:
# without an explicit convention, PostgreSQL auto-generates constraint
# names that vary between dev/prod, breaking ``alembic --autogenerate``
# diffs. Reference: https://docs.sqlalchemy.org/en/20/core/constraints.html
# (Configuring Constraint Naming Conventions).

NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """SQLAlchemy 2.x declarative base shared by every model.

    Models inherit from :class:`Base` so that they all share a single
    :class:`sqlalchemy.MetaData` object, which carries the project's
    stable constraint-naming convention. This keeps Alembic
    autogenerated migrations deterministic across environments.

    Models live under :mod:`app.models` and re-export from
    :mod:`app.models.__init__` for Alembic's ``target_metadata``
    discovery.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


# ---------------------------------------------------------------------------
# SQLAlchemy Wrapper - bare SQLAlchemy 2.x, no flask-sqlalchemy
# ---------------------------------------------------------------------------


class SQLAlchemy:
    """Thin wrapper around bare SQLAlchemy 2.x for Flask integration.

    Used like a Flask extension:

        db = SQLAlchemy()
        # ... later in create_app():
        db.init_app(app)

    After :meth:`init_app` has been called, the wrapper exposes:

    * ``self.engine`` - :class:`sqlalchemy.Engine` (connection pool).
    * ``self.Session`` - :class:`sqlalchemy.orm.sessionmaker` factory.
    * ``self.metadata`` - :class:`sqlalchemy.MetaData` (``Base.metadata``).
    * ``self.Base`` - :class:`sqlalchemy.orm.DeclarativeBase` subclass.

    Session lifecycles are owned by service-layer code via explicit
    ``with db.session() as session:`` blocks rather than by automatic
    Flask teardown handlers - this is intentional per AAP section
    0.5.3 ("Service functions own transactions").

    The class is intentionally minimal: no automatic teardown, no
    request-scoped session proxies, no query property. These would all
    obscure the explicit-transaction discipline the project requires.
    """

    def __init__(self) -> None:
        """Construct an unbound wrapper.

        ``self.engine`` and ``self.Session`` raise :class:`RuntimeError`
        until :meth:`init_app` has been called. The ``metadata`` and
        ``Base`` attributes are bound at construction time so that
        callers (notably ``backend/migrations/env.py``) can introspect
        the schema without instantiating a Flask app first.
        """
        self._engine: Engine | None = None
        self._session_factory: sessionmaker[SQLAlchemySession] | None = None
        # Expose ``metadata`` and ``Base`` at instance level so that
        # consumers (Alembic's env.py, ad-hoc scripts, tests) can call
        # e.g. ``db.metadata.create_all(engine)`` without importing
        # ``Base`` directly.
        self.metadata: MetaData = Base.metadata
        self.Base: type[DeclarativeBase] = Base

    @property
    def engine(self) -> Engine:
        """Return the bound SQLAlchemy :class:`Engine`.

        Raises:
            RuntimeError: If accessed before :meth:`init_app` has been
                called. This is a programmer error - it indicates the
                application factory has not finished building the app.
        """
        if self._engine is None:
            raise RuntimeError(
                "SQLAlchemy.engine accessed before init_app(app); "
                "ensure create_app() has been called."
            )
        return self._engine

    @property
    def Session(self) -> sessionmaker[SQLAlchemySession]:  # noqa: N802 - Flask-extension idiom
        """Return the bound :class:`sessionmaker` factory.

        Raises:
            RuntimeError: If accessed before :meth:`init_app` has been
                called.

        Note:
            The capitalised attribute name follows the Flask-SQLAlchemy
            convention so that callers can write ``db.Session()`` to
            instantiate a session, mirroring the public API contract
            in the file's exports schema.
        """
        if self._session_factory is None:
            raise RuntimeError(
                "SQLAlchemy.Session accessed before init_app(app); "
                "ensure create_app() has been called."
            )
        return self._session_factory

    def init_app(self, app: Flask) -> None:
        """Construct the Engine and Session factory from the app config.

        Reads the following Flask config keys:

        * ``DATABASE_URL`` (required) - SQLAlchemy DSN, e.g.
          ``postgresql+psycopg://user:pass@host:5432/dbname``.
        * ``DB_POOL_SIZE`` (default 5) - per-process connection pool
          ceiling. Honored for QueuePool-backed dialects (PostgreSQL,
          MySQL); silently dropped for ``sqlite:///:memory:`` because
          SingletonThreadPool does not accept these kwargs.
        * ``DB_MAX_OVERFLOW`` (default 10) - additional transient
          connections allowed beyond ``pool_size``. Same
          QueuePool-only caveat as ``DB_POOL_SIZE``.
        * ``DB_POOL_RECYCLE`` (default 1800) - seconds after which
          pooled connections are recycled. Mitigates idle-disconnect
          timeouts on managed Postgres (RDS).
        * ``DB_ECHO`` (default ``False``) - if ``True``, SQLAlchemy
          logs every statement to the configured ``sqlalchemy.engine``
          logger. Use sparingly; verbose.

        Always applied (not configurable):

        * ``pool_pre_ping=True`` - validates each connection on checkout
          to detect stale sockets after RDS failover or network
          interruption. Production-resilience requirement.
        * ``future=True`` - opts into SQLAlchemy 2.x execution semantics.
        * ``autoflush=False`` and ``expire_on_commit=False`` on the
          Session factory - enables service-layer code to read attribute
          values from ORM-loaded objects after ``commit()`` without
          surprise re-fetches.

        Idempotent: a second call replaces the prior Engine and Session
        factory. Tests rely on this for app teardown/setup cycles.

        Side effects:
            Stashes ``self`` on ``app.extensions["db"]`` so that handlers
            preferring ``current_app.extensions["db"]`` over the
            module-level ``db`` singleton can find the same instance.

        Args:
            app: The Flask application being initialised.

        Raises:
            KeyError: If ``DATABASE_URL`` is absent from the app config.
                The Flask config dict is the authoritative source of
                configuration; missing keys here indicate a setup error
                in the application factory and must surface immediately
                rather than be silently defaulted.
        """
        dsn = app.config["DATABASE_URL"]

        # Build the engine kwargs. ``pool_size`` and ``max_overflow`` are
        # specific to :class:`sqlalchemy.pool.QueuePool` (the default for
        # PostgreSQL, MySQL, etc.). They are NOT accepted by
        # :class:`SingletonThreadPool` - which SQLAlchemy selects
        # automatically for ``sqlite:///:memory:`` DSNs. Passing them
        # would raise ``TypeError: Invalid argument(s) ...`` from
        # ``create_engine``. We therefore detect the in-memory SQLite
        # case and skip those kwargs - keeping the wrapper usable for
        # ad-hoc tests and notebook prototyping while preserving the
        # production-ready QueuePool tuning for the (Postgres) production
        # path.
        engine_kwargs: dict[str, object] = {
            "pool_recycle": app.config.get("DB_POOL_RECYCLE", 1800),
            "pool_pre_ping": True,
            "echo": app.config.get("DB_ECHO", False),
            "future": True,
        }
        url = make_url(dsn)
        is_sqlite_memory = url.drivername.startswith("sqlite") and (
            url.database is None or url.database in {"", ":memory:"}
        )
        if not is_sqlite_memory:
            engine_kwargs["pool_size"] = app.config.get("DB_POOL_SIZE", 5)
            engine_kwargs["max_overflow"] = app.config.get("DB_MAX_OVERFLOW", 10)

        self._engine = create_engine(dsn, **engine_kwargs)
        self._session_factory = sessionmaker(
            bind=self._engine,
            autoflush=False,
            autocommit=False,
            expire_on_commit=False,
            class_=SQLAlchemySession,
        )

        # Stash the wrapper on the Flask app for handlers that prefer
        # ``current_app.extensions["db"]`` over the module-level
        # singleton. This is a Flask-extension convention.
        app.extensions["db"] = self

    def session(self) -> SQLAlchemySession:
        """Return a new :class:`Session` instance.

        Convenience wrapper around ``self.Session()``. Service-layer
        code is expected to use this in a ``with`` block::

            with db.session() as session:
                with session.begin():
                    session.add(record)
                    emit_audit_event(session, ...)

        The outer ``with`` ensures the session is closed; the inner
        ``with session.begin():`` ensures the transaction is committed
        on success and rolled back on exception. This pattern is the
        canonical "service functions own transactions" idiom from the
        AAP.

        Returns:
            A fresh :class:`SQLAlchemySession` bound to the configured
            engine.

        Raises:
            RuntimeError: If accessed before :meth:`init_app` has been
                called (propagated from the ``Session`` property).
        """
        return self.Session()

    def dispose(self) -> None:
        """Tear down the engine and clear the session factory.

        Releases all pooled connections by calling
        :meth:`Engine.dispose`, then clears the cached engine and
        session factory so that subsequent attribute access raises
        :class:`RuntimeError` again (the same behaviour as a freshly
        constructed wrapper).

        Used by tests for inter-test cleanup and by graceful-shutdown
        handlers that want to drain the connection pool before the
        worker exits.

        Idempotent: calling :meth:`dispose` twice is a no-op on the
        second invocation.
        """
        if self._engine is not None:
            self._engine.dispose()
            self._engine = None
            self._session_factory = None


# ---------------------------------------------------------------------------
# Authlib OAuth Client + Provider Registration Helper
# ---------------------------------------------------------------------------
# ``oauth`` is the registration table for OAuth providers. Binding to
# a specific Flask app happens via ``oauth.init_app(app)`` from the
# application factory; per-app provider registration (e.g., Google) is
# deferred to ``init_oauth_clients(app, oauth)`` so test apps can
# choose whether to register Google based on whether credentials are
# present in the test config.

oauth: OAuth = OAuth()


def init_oauth_clients(app: Flask, oauth_client: OAuth) -> None:
    """Register OAuth providers on the supplied Authlib client.

    Currently registers exactly one provider:

    * ``google`` - Google OAuth 2.0 / OpenID Connect, configured via
      OpenID Connect discovery (``server_metadata_url``) so the
      authorization, token, and JWKS endpoints are fetched at first
      use rather than hard-coded.

    Reads the following Flask config keys (already populated by
    :class:`app.config.BaseConfig` from the corresponding environment
    variables):

    * ``GOOGLE_OAUTH_CLIENT_ID`` - Google OAuth client identifier.
    * ``GOOGLE_OAUTH_CLIENT_SECRET`` - Google OAuth client secret.

    If either credential is empty (the testing/dev path when Google
    OAuth is not configured), this function logs a structured warning
    and returns without registering the provider. This keeps the test
    suite and unconfigured local-dev environments from raising at
    application factory time.

    Args:
        app: The Flask application supplying the configuration.
        oauth_client: The Authlib :class:`OAuth` registration table to
            mutate. Passed in (rather than referencing the module-level
            ``oauth`` singleton directly) so that test code can supply
            a fresh, isolated client when needed.

    Returns:
        None. Side effect is registration on the supplied
        ``oauth_client`` (visible in ``oauth_client._registry``).

    Raises:
        Nothing under normal operation. Any errors raised by Authlib
        during ``register()`` (e.g., malformed kwargs) propagate
        directly to the caller.
    """
    client_id = app.config.get("GOOGLE_OAUTH_CLIENT_ID")
    client_secret = app.config.get("GOOGLE_OAUTH_CLIENT_SECRET")
    if not client_id or not client_secret:
        # Use a per-call logger here to avoid coupling this helper to
        # the module-level ``logger`` singleton's namespace - keeps the
        # warning attributable to the extensions module specifically.
        structlog.get_logger("app.extensions").warning(
            "google_oauth_credentials_missing",
            detail=(
                "GOOGLE_OAUTH_CLIENT_ID and/or GOOGLE_OAUTH_CLIENT_SECRET "
                "are not configured; Google OAuth login will be disabled."
            ),
        )
        return

    # ``client_kwargs`` is forwarded to Authlib's underlying OAuth2
    # client (and the ``OAuth2Session`` it composes). Each key carries
    # a distinct security/resilience invariant per AAP Section 0.4.5
    # and Section 0.7.4:
    #
    # * ``scope`` -- OpenID Connect minimal scope set required for
    #   email-based user upsert (``openid`` enables OIDC, ``email``
    #   surfaces the verified email claim, ``profile`` surfaces the
    #   ``name`` claim used for ``User.display_name``).
    # * ``code_challenge_method`` -- enables PKCE per RFC 7636 with
    #   the SHA-256 challenge method (``S256``). Authlib's
    #   ``OAuth2Session`` checks this attribute when building the
    #   authorization URL: when ``code_challenge_method == "S256"``
    #   it auto-generates a per-flow ``code_verifier``, computes
    #   ``code_challenge = base64url(SHA256(code_verifier))``, and
    #   includes ``code_challenge`` and ``code_challenge_method`` in
    #   the redirect URL. The verifier is persisted in the framework
    #   session and replayed at the token-exchange step. Without
    #   this key Authlib silently SKIPS PKCE -- a stolen
    #   authorization code could be exchanged for tokens by an
    #   attacker who never possessed the verifier. AAP Section 0.4.5
    #   mandates PKCE for the Google OAuth flow.
    # * ``default_timeout`` -- caps every HTTP request the OAuth2
    #   session issues to Google (token exchange, JWKS fetch via
    #   discovery, and the OIDC discovery document itself) at 10
    #   seconds. Without an explicit timeout the underlying
    #   ``requests.Session`` would block indefinitely on a slow
    #   provider, causing the Gunicorn worker to retire only when
    #   its own ``--timeout 30`` fires (taking the worker out of
    #   rotation for one full request). 10 s is comfortably above
    #   Google's typical sub-second response while preventing
    #   pathological hangs.
    oauth_client.register(
        name="google",
        client_id=client_id,
        client_secret=client_secret,
        server_metadata_url=("https://accounts.google.com/.well-known/openid-configuration"),
        client_kwargs={
            "scope": "openid email profile",
            "code_challenge_method": "S256",
            "default_timeout": 10,
        },
    )


# ---------------------------------------------------------------------------
# Structlog Logger Singleton
# ---------------------------------------------------------------------------
# Bound at module import; picks up the structlog configuration applied
# during ``app.create_app()`` lazily (the first time it logs). This
# satisfies the AAP requirement for a module-level logger singleton
# without preventing handlers from preferring ``structlog.get_logger(__name__)``
# for finer-grained namespacing.

logger: structlog.stdlib.BoundLogger = structlog.get_logger("app")


# ---------------------------------------------------------------------------
# Prometheus Client Registry
# ---------------------------------------------------------------------------
# Application-owned metrics registry, deliberately separate from
# ``prometheus_client.REGISTRY`` (the default global). Reasons:
#
# 1. Test isolation: tests construct multiple Flask apps via
#    ``create_app()``. The default ``REGISTRY`` is a singleton; a
#    second registration of the same metric name (e.g.,
#    ``Counter("http_requests_total", ...)``) raises
#    ``ValueError: Duplicated timeseries``. A dedicated
#    ``CollectorRegistry`` sidesteps this entirely.
# 2. Namespace hygiene: keeps the application's metric surface
#    distinct from any unrelated collectors that downstream
#    libraries might inadvertently register on the default
#    ``prometheus_client.REGISTRY``.
#
# This registry is consumed by :func:`app.observability.metrics.init_metrics`
# (which mounts the ``/metrics`` route and registers the application's
# counters, histograms, and gauges).

metrics_registry: CollectorRegistry = CollectorRegistry()


# ---------------------------------------------------------------------------
# Built-in Process / Platform / GC Collectors (per QA Checkpoint 10 Issue 5)
# ---------------------------------------------------------------------------
# ``prometheus_client``'s built-in ``ProcessCollector``,
# ``PlatformCollector``, and ``GCCollector`` auto-register against the
# DEFAULT global ``REGISTRY`` only at module import time. Because this
# project uses a dedicated ``metrics_registry`` (above) for test
# isolation, those collectors do NOT show up at the ``/metrics``
# endpoint without explicit registration here. The ``ECS CloudWatch
# container insights`` metrics fill the gap in production but
# Prometheus-native operator tooling (Grafana, Alertmanager, pgwatch,
# kube-prometheus-stack) expects ``process_resident_memory_bytes``,
# ``process_open_fds``, ``process_cpu_seconds_total``, and the
# ``python_*`` namespace at minimum.
#
# Each collector is constructed exactly once at module import time,
# binding it to the custom ``metrics_registry``. The constructors are
# idempotent in the sense that the registry rejects duplicate
# collectors with a ``ValueError`` if module re-import ever fires
# (which it should not under normal Python import semantics).
#
# A defensive try/except guard tolerates the (rare, dev-only) case
# where the runtime is not the canonical CPython interpreter or where
# ``/proc`` is unavailable (e.g., macOS local development without
# /proc). In that case the platform collector is still safe; only
# ProcessCollector is /proc-bound on POSIX. The except block silently
# logs the failure rather than crashing the application factory.

# ValueError covers "collector already registered" (which would only
# occur if module re-import ever fired under unusual test harnesses);
# OSError covers /proc not mounted (rare on CPython on Linux containers
# but defensible on macOS local development).
with contextlib.suppress(ValueError, OSError):  # pragma: no cover - defensive
    ProcessCollector(registry=metrics_registry)

with contextlib.suppress(ValueError):  # pragma: no cover - defensive
    PlatformCollector(registry=metrics_registry)

with contextlib.suppress(ValueError):  # pragma: no cover - defensive
    GCCollector(registry=metrics_registry)


# ---------------------------------------------------------------------------
# SQLAlchemy Wrapper Singleton
# ---------------------------------------------------------------------------
# Defined at the very end of the module so that the ``Base`` class and
# the ``SQLAlchemy`` class definition above are guaranteed to exist
# before the singleton is constructed. The singleton is bound at
# import time but remains unbound (no engine, no session factory)
# until the application factory calls ``db.init_app(app)``.

db: SQLAlchemy = SQLAlchemy()
